# Site settings
theme: jekyll-theme-cayman
title: Energy
author:
  name: Christoph Trautwein
  url: https://github.com/Energy
  twitter_username: trautw
  github_username:  trautw
  email: ch.trautwein@bmail.com
description: > # this means to ignore newlines until "tagline:"
  Solving the energy problem has to be the next big thing 
tagline: > # this means to ignore newlines until "baseurl:"
  Solving the energy problem. 
  Motivation and ways to go
baseurl: "/Energy" # the subpath of your site, e.g. /blog/
url: "https://trautw.github.io" # the base hostname & protocol for your site

# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
